[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.vagrant-sync]
command = "vagrant"
args = ["rsync"]

[tasks.run]
dependencies = ["build", "vagrant-sync"]
command = "vagrant"
args = ["ssh", "firewall", "-c", "sudo /vagrant/target/release/svalinn-daemon"]
