[package]
name = "svalinn-shared"
version = { workspace = true }
edition = { workspace = true }

[features]
default = ["std"]
std = ["dep:serde", "dep:aya"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"], optional = true }
aya = { version = "0.13.1", optional = true }
